name: mw

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/mw.yml'
  schedule:
    - cron: '50 22 * * *'

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "mw"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          echo $(date) > VERSION
          git config user.name $(git log -1 --pretty=format:'%an')
          git config user.email $(git log -1 --pretty=format:'%ae')
          git add .
          git diff-index --quiet HEAD || git commit -m "update"
          git push

          sed -i 's|latest|github:movie-web/providers|g' package.json
          npm install
          sed -i 's|console.log(.*);||g' node_modules/@movie-web/providers/lib/index.mjs
          sed -i 's|console.log(.*)||g' node_modules/@movie-web/providers/lib/index.mjs
          npm install -g pkg
          pkg -t node18-macos-x64,node18-linux-x64,node18-alpine-x64 index.js
          mv index-macos movie-web && tar -zcvf mw-macos-amd64.tar.gz movie-web
          mv index-linux mw && tar -zcvf mw-linux-amd64.tar.gz mw
          mv index-alpine mw && tar -zcvf mw-alpine-amd64.tar.gz mw
          echo "VERSION=$(date +%Y%m%d.%H%M%S)" >> $GITHUB_ENV

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mw-macos-amd64.tar.gz
          asset_name: mw-macos-amd64.tar.gz
          asset_content_type: application/gzip

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mw-linux-amd64.tar.gz
          asset_name: mw-linux-amd64.tar.gz
          asset_content_type: application/gzip

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mw-alpine-amd64.tar.gz
          asset_name: mw-alpine-amd64.tar.gz
          asset_content_type: application/gzip
          
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
        with:
          repository: movie-web/movie-web
          
      - uses: actions/setup-node@v4
      - env:
          VITE_BASE_URL: /mw/
          VITE_CORS_PROXY_URL: ${{ secrets.CORS_PROXY_URL }}
          VITE_TMDB_READ_API_KEY: ${{ secrets.TMDB_READ_API_KEY }}
        run: |
          sed -i 's|fetch("/ping.txt"|fetch("/mw/ping.txt"|g' src/hooks/usePing.ts
          npm i -g pnpm
          pnpm install
          pnpm run build
          
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - uses: actions/deploy-pages@v4

      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
