name: mw

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/mw.yml'
  schedule:
    - cron: '50 22 * * *'

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "mw"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - run: |
          echo $(date) > VERSION
          git config user.name $(git log -1 --pretty=format:'%an')
          git config user.email $(git log -1 --pretty=format:'%ae')
          git add .
          git diff-index --quiet HEAD || git commit -m "update"
          git push
          
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
        with:
          repository: movie-web/movie-web
          
      - uses: actions/setup-node@v4
      - env:
          VITE_BASE_URL: /mw/
          VITE_CORS_PROXY_URL: ${{ secrets.CORS_PROXY_URL }}
          VITE_TMDB_READ_API_KEY: ${{ secrets.TMDB_READ_API_KEY }}
        run: |
          sed -i 's|fetch("/ping.txt"|fetch("/mw/ping.txt"|g' src/hooks/usePing.ts
          npm i -g pnpm
          pnpm install
          pnpm run build
          
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - uses: actions/deploy-pages@v4

      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
